### ISSUE TITLE
Formatting of UsecTimestamps is numeric instead of date string

### ISSUE THREAD

**Issue by jbnas** [Nastel/TNT4J#29]
When logging UsecTimestamps, the values are formatted as longs instead of date strings.  For example, calling:

`logger.info("{0}", UsecTimestamp.now());`

the value is formatted as a long (e.g. 1583166154000000) instead of a date/time string (e.g. 2020-03-02 11:22:34.000000)

Note that UsecTimestamp extends java.lang.Number.  May a clue as to why.  This was not the behavior in release 2.11.

**Comment by kausandr** [comment]
Your note regarding UsecTimestamp is extended from Number is right. But it was like this long time already (even prior version 2.11).

This point that currently you have updated either Java version or logger version. And it picks `UsecTimestamp.doubleValue()` instead of `UsecTimestamp.toString()` when formatting log entry message (like MessageFormat.format() does). 

Try `logger.info("{0}", UsecTimestamp.now().toString());` to check if you'll get expected date formatted value. Then you'll have to add `.toString()` for every UsecTimestamp value logging.

**Comment by jbnas** [comment]
Sorry, seems like this has always been the case.  Could have sworn that it was behaving differently than previous versions.
